/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import treeIntersection.BinarySearchTree;
import treeIntersection.BinaryTree;
import treeIntersection.TreeIntersection;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class App {
    public static void main(String[] args) {

        HashTable<String> hashTable = new HashTable<>(10);


        hashTable.set(1, "One");
        hashTable.set(2, "Two");
        hashTable.set(3, "Three");
        hashTable.set(9, "Nine");


        System.out.println("Value 1: " + hashTable.get(1));
        System.out.println("Value 2: " + hashTable.get(2));
        System.out.println("Value 3: " + hashTable.get(3));
        System.out.println("Value 4: " + hashTable.get(4));
        System.out.println("Value 9: " + hashTable.get(9));

        System.out.println();

        System.out.println("Has 2 ? " + hashTable.has(2));
        System.out.println("Has 4 ?  " + hashTable.has(4));

        List<Integer> keys = hashTable.keys();

        System.out.println("keys: " + keys);

        System.out.println();
        System.out.println("---- Code Challenge 31 ----");

        String test = "Once upon a time, there was a brave princess who...";
        String test2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        String test3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";


        HashTable<String> stringHashTable = new HashTable<>(test.length());
        System.out.println(stringHashTable.repeatedWord(test));
        System.out.println(stringHashTable.repeatedWord(test2));
        System.out.println(stringHashTable.repeatedWord(test3));


        System.out.println();
        System.out.println("---- Code Challenge 32 ----");



        BinarySearchTree<Integer> bst1 = new BinarySearchTree<Integer>();
        bst1.insert(10);
        bst1.insert(5);
        bst1.insert(15);
        bst1.insert(3);
        bst1.insert(7);
        bst1.insert(18);

        BinarySearchTree<Integer> bst2 = new BinarySearchTree<Integer>();

        bst2.insert(11);
        bst2.insert(5);
        bst2.insert(20);
        bst2.insert(3);
        bst2.insert(7);
        bst2.insert(16);

        TreeIntersection treeIntersection =new TreeIntersection();

        HashTable<Integer> intersectionResult = treeIntersection.tree_Intersection(bst1,bst2);

        for(int i=0;i<intersectionResult.size;i++){
            if(intersectionResult.get(i) != null)
            System.out.print(intersectionResult.get(i) + " ");
        }


        System.out.println();
        System.out.println();
        System.out.println("---- Code Challenge 33 ----");


        HashMap<String,String> left = new HashMap<>();
        HashMap<String,String> right = new HashMap<>();

        left.put("diligent","employed");
        left.put("fond","enamored");
        left.put("guide","usher");
        left.put("outfit","grab");
        left.put("wrath","anger");

        right.put("diligent","idle");
        right.put("fond","averse");
        right.put("guide","follow");
        right.put("flow","jam");
        right.put("wrath","delight");

        ArrayList<String> result = hashTable.leftJoin(left,right);

        System.out.println(result);


    }
}
