/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

public class App {

    public static void main(String[] args) {
        Graph<String> graph = new Graph<>(10);


        Vertex<String> a = graph.addVertex("A");
        Vertex<String> b = graph.addVertex("B");
        Vertex<String> c = graph.addVertex("C");
        Vertex<String> d = graph.addVertex("D");


        graph.addEdge(a, b, 1);
        graph.addEdge(b, c, 2);
        graph.addEdge(c, a, 3);
        graph.addEdge(d, a, 4);

        System.out.println("Graph:\n" + graph);

        System.out.println("Vertices: " + graph.getVertices());


        System.out.println("Neighbors of A: " +  graph.getNeighbors(a));
        System.out.println("Neighbors of B: " +  graph.getNeighbors(b));
        System.out.println("Neighbors of C: " +  graph.getNeighbors(c));
        System.out.println("Neighbors of D: " +  graph.getNeighbors(d));


        System.out.println("");
        System.out.println("-----Code Challenge 36-----");
        List<Vertex<String>> result = graph.breadthFirstTraversal(a);
        for (Vertex<String> vertex : result) {
            System.out.print(vertex.getValue() + " ");
        }

        System.out.println("");
        System.out.println("-----Code Challenge 37-----");

        HashMap<String, HashMap<String, Integer>> flights = new HashMap<>();
        flights.put("Metroville", new HashMap<String, Integer>(){{put("Pandora", 82);}});
        flights.put("Arendelle", new HashMap<String, Integer>(){{put("New Monstropolis", 45);}});
        flights.put("New Monstropolis", new HashMap<String, Integer>(){{put("Naboo", 70);}});
        flights.put("Naboo", new HashMap<String, Integer>(){{put("Pandora", 90);}});

        String[] trip1 = {"Metroville", "Pandora"};
        String[] trip2 = {"Arendelle", "New Monstropolis", "Naboo"};
        String[] trip3 = {"Narnia", "Arendelle", "Naboo"};


        System.out.println(graph.businessTrip(flights, trip1));
        System.out.println(graph.businessTrip(flights, trip2));
        System.out.println(graph.businessTrip(flights, trip3));


    }
}
