/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {
        Graph<String> graph = new Graph<>(10);


        Vertex<String> a = graph.addVertex("A");
        Vertex<String> b = graph.addVertex("B");
        Vertex<String> c = graph.addVertex("C");
        Vertex<String> d = graph.addVertex("D");


        graph.addEdge(a, b, 1);
        graph.addEdge(b, c, 2);
        graph.addEdge(c, a, 3);
        graph.addEdge(d, a, 4);



        System.out.println("Graph:\n" + graph);

        System.out.println("Vertices: " + graph.getVertices());


        System.out.println("Neighbors of A: " +  graph.getNeighbors(a));
        System.out.println("Neighbors of B: " +  graph.getNeighbors(b));
        System.out.println("Neighbors of C: " +  graph.getNeighbors(c));
        System.out.println("Neighbors of D: " +  graph.getNeighbors(d));





    }
}
