/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {

        int[] list = {3,4,2,2,5,6,7,1};
        MergeSort mergeSort = new MergeSort();
        int[] sortedList= mergeSort.sort(list);

        System.out.println(Arrays.toString(sortedList));

    }
}
