/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comparison;

public class App {


    public static void main(String[] args) {


        String[] movieGenres = {"drama", "romantic"};
        Movie movie1 = new Movie("Titanic", 1999, movieGenres);
        Movie movie2 = new Movie("The Other Zoey", 2009, movieGenres);
        Movie movie3 = new Movie("Awareness", 2010, movieGenres);
        Movie movie4 = new Movie("The fault in our stars", 2005, movieGenres);

        Movie[] movies = {movie1, movie2, movie3,movie4};

        Comparision comparision = new Comparision();

        Movie[] sortedMovies = comparision.sortByYear(movies);
        System.out.println("Sorting By Year");
        for (Movie movie : sortedMovies) {
            System.out.print(movie.getTitle() + ", ");

        }

        System.out.println(); System.out.println();
        System.out.println("Sorting By title: ");
        Movie[] sortedMoviesByTitle= comparision.sortByTitle(movies);

        for (Movie movie : sortedMoviesByTitle) {
            System.out.print(movie.getTitle() + ", ");

        }

    }
}
